const labels = { MONTH: '1 tháng', SEMESTER: '1 học kỳ', YEAR: '1 năm' }
const statuses = { PAID: 'Đã thanh toán', PENDING: 'Chờ thanh toán', FAILED: 'Thất bại', EXPIRED: 'Đã hết hạn' }

export default function PaymentsTab({ payments = [], summary = {}, query, setQuery, status, setStatus }) {
  return <div className="space-y-5">
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Card icon="payments" label="Doanh thu đã xác nhận" value={`${Number(summary.totalRevenue || 0).toLocaleString('vi-VN')}đ`} tone="emerald"/><Card icon="check_circle" label="Giao dịch thành công" value={summary.paidCount || 0} tone="blue"/><Card icon="schedule" label="Đang chờ thanh toán" value={summary.pendingCount || 0} tone="amber"/><Card icon="error" label="Thất bại / hết hạn" value={summary.failedCount || 0} tone="rose"/></div>
    <section className="rounded-2xl border border-slate-100 bg-white p-5 shadow-sm"><div className="mb-4 flex flex-col justify-between gap-3 md:flex-row md:items-center"><div><h2 className="font-bold text-[#141b2b]">Lịch sử giao dịch VNPay</h2><p className="mt-1 text-xs text-slate-500">Chỉ đơn thành công được tính vào doanh thu.</p></div><div className="flex gap-2"><input className="rounded-lg border border-slate-200 px-3 py-2 text-xs" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Mã đơn, email, tên..."/><select className="cursor-pointer rounded-lg border border-slate-200 px-3 py-2 text-xs" value={status} onChange={(e) => setStatus(e.target.value)}><option value="">Tất cả</option>{Object.keys(statuses).map((key) => <option key={key} value={key}>{statuses[key]}</option>)}</select></div></div><div className="overflow-x-auto"><table className="w-full min-w-210 text-left text-xs"><thead className="bg-[#f1f3ff] text-slate-600"><tr><th className="p-3">Người thanh toán</th><th className="p-3">Gói / tiền</th><th className="p-3">Mã đơn</th><th className="p-3">Mã VNPay</th><th className="p-3">Thời gian</th><th className="p-3">Trạng thái</th></tr></thead><tbody className="divide-y divide-slate-100">{payments.length === 0 ? <tr><td className="p-8 text-center text-slate-500" colSpan="6">Chưa có giao dịch phù hợp.</td></tr> : payments.map((p) => <tr key={p.id}><td className="p-3"><strong className="block text-slate-800">{p.user?.fullName || '—'}</strong><span className="text-slate-500">{p.user?.email || '—'}</span></td><td className="p-3"><strong>{labels[p.plan] || p.plan}</strong><span className="block font-bold text-[#00288e]">{Number(p.amount).toLocaleString('vi-VN')}đ</span></td><td className="p-3 font-mono text-[11px]">{p.txnRef}</td><td className="p-3 font-mono text-[11px]">{p.vnpTransactionNo || '—'} {p.bankCode || ''}</td><td className="p-3 text-slate-500">{new Date(p.paidAt || p.createdAt).toLocaleString('vi-VN')}</td><td className="p-3"><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${p.status === 'PAID' ? 'bg-emerald-100 text-emerald-800' : p.status === 'PENDING' ? 'bg-amber-100 text-amber-800' : 'bg-rose-100 text-rose-700'}`}>{statuses[p.status] || p.status}</span></td></tr>)}</tbody></table></div></section>
  </div>
}
function Card({ icon, label, value, tone }) { const colors = { emerald: 'bg-emerald-50 text-emerald-700', blue: 'bg-blue-50 text-blue-800', amber: 'bg-amber-50 text-amber-800', rose: 'bg-rose-50 text-rose-700' }; return <div className={`rounded-2xl p-5 ${colors[tone]}`}><span className="material-symbols-outlined">{icon}</span><p className="mt-2 text-xs font-semibold">{label}</p><strong className="block text-2xl">{value}</strong></div> }
